### ISSUE TITLE
No output when running PraatSauce on Windows

### ISSUE THREAD

**Issue by terriyu** [kirbyj/praatsauce#3]
I tried running PraatSauce on the madurese files in this repo. I wanted to try out the code. But I got an output of `Analysis complete: <0> tokens measured.` I'm running Windows 7 and used the latest version of Praat. I used all the default values in the parameter windows, only changing the directories to something like `C:\Users\me\Desktop\praatsauce\comp\madurese`. Is Praat not finding the wav files? I figure there must be something simple I'm missing. Any tips would be appreciated!

**Comment by kirbyj** [comment]
You are probably missing the trailing forward slash in the path. Try 

C:\Users\me\Desktop\praatsauce\comp\madurese\

**Comment by terriyu** [comment]
Thank you for the quick response. That solved the problem.

**Comment by kirbyj** [comment]
I've updated praatsauce and shellsauce to include trailing slashes, since it doesn't matter if they are doubled up. If you have a chance to test this patch on a Windows machine, that would be great.

**Comment by terriyu** [comment]
I tested it on my Windows 7 machine. It works whether or not I use trailing slashes or not. Nice fix! I should note that I had to change to interval tier to `1`. The default is set to `2`. If I leave the interval tier set to `2`, then I get the error `Your tier number (2) should not be greater than the number of tiers (1).`
