### ISSUE TITLE
"Script line 662 not completed"

### ISSUE THREAD

**Issue by LilithOtranto** [kirbyj/praatsauce#6]
Hi,

I am trying to use praatsauce on my data but when running the script praatSauce.praat, I get the following message when it's on small recordings :

Unknown Value
"PRAAT\test\"for boolean "listenToSound".
Spcript "K:\scripts-praat\praat-sauce-master\scr\formantMeasures.praat" not comleted.
Script line 662 not performed or completed:
"execute formantMeasures.praat 'interval tier' 'current interval' 'windowPosition' 'windowLength' 'manualCheck' 'saveAsEPS' 'useBandwidthFormula' 'useExistingFormants' 'inputdir$' 'basename$' 'listenToSound' 'timeStep' 'maxNumFormants' 'maxFormantHz' 'preHemphFrom' 'f1ref' 'f2ref' 'f3ref' 'spectrogramWindow' 'measure' 'timepoints' 'points' 'formantTracking'"
Please change something in the command window "Run script: Directory and measures", or click Cancel in that window.

When the recordings are longer, praat just crashes.

Does anyone ever had this problem, or/and knows what I could fix in the command window ?

**Comment by kirbyj** [comment]
What is the full path to the file/filename you are providing Praatsauce?

**Comment by NaHuGithub** [comment]
> What is the full path to the file/filename you are providing Praatsauce?

Hi Kirby, 

I've run into the same issue when running Praatsauce. 

I'm pretty sure the path that I provided is correct as the first pair of sound and textgrid files are read into the object window, and Pitch, Formant, and Harmonicity objects are generated. However, after that, the error message in the post appeared. I'm using Praat version 6.0.36. Any assistance you can provide would be greatly appreciated. 

best

**Comment by NaHuGithub** [comment]
> > I'm pretty sure the path that I provided is correct as the first pair of sound and textgrid files are read into the object window, and Pitch, Formant, and Harmonicity objects are generated.
> 
> The issue is sometimes not whether the path is correct, but what characters are in the pathname/filename.

Ah, I see. Not sure if I am allowed to paste the full path here. But what are the illegal characters?

**Comment by NaHuGithub** [comment]
> > I'm pretty sure the path that I provided is correct as the first pair of sound and textgrid files are read into the object window, and Pitch, Formant, and Harmonicity objects are generated.
> 
> The issue is sometimes not whether the path is correct, but what characters are in the pathname/filename.

Ok, so I created a new folder path without any characters such as dashes or underscores (although I'm not sure which one was causing the issue). After making this adjustment, the script ran smoothly without any problems. Thank you for directing me towards the right solution.
